version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: hse_postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=paSSw0rd
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - hse_network

  redis:
    image: redis:latest
    container_name: hse_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - hse_network

  redpanda:
    image: redpandadata/redpanda:latest
    container_name: hse_redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - "1G"
      - --reserve-memory
      - "0M"
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"
      - "8081:8081" # Для Admin API, если понадобится
    networks:
      - hse_network

  console:
    image: redpandadata/console:latest
    container_name: hse_redpanda_console
    environment:
      KAFKA_BROKERS: redpanda:29092 # Имя сервиса Redpanda в Docker Compose
    ports:
      - "8080:8080"
    depends_on:
      - redpanda
    networks:
      - hse_network

  backend-app:
    build: .
    container_name: hse_fastapi_app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - postgres-db
      - redpanda # Приложение теперь зависит от Redpanda
      - redis
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:paSSw0rd@postgres-db:5432/postgres
      - KAFKA_BOOTSTRAP_SERVERS=redpanda:29092 # Передаем адрес Kafka в приложение
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - hse_network

volumes:
  postgres_data:

networks:
  hse_network:
    driver: bridge
